name: firebase_app_installations_web
description: The web implementation of firebase_app_installations.
version: 0.1.2+1
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_installations/firebase_app_installations_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_installations/firebase_app_installations_web

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  _flutterfire_internals:
    path: ../../_flutterfire_internals
  firebase_app_installations_platform_interface:
    path: ../firebase_app_installations_platform_interface
  firebase_core:
    path: ../../firebase_core/firebase_core
  firebase_core_web:
    path: ../../firebase_core/firebase_core_web
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  firebase_core_platform_interface:
    path: ../../firebase_core/firebase_core_platform_interface
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAppInstallationsWeb
        fileName: firebase_app_installations_web.dart
